-- Script SQL para criar a estrutura do banco de dados no Supabase
-- Execute este script no SQL Editor do Supabase (Dashboard -> SQL Editor)

-- 1. Criação do Tipo ENUM para Perfis de Usuário
CREATE TYPE user_role AS ENUM ('morador', 'zelador', 'comgas');

-- 2. Tabela de Condomínios
CREATE TABLE IF NOT EXISTS condominios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(100) NOT NULL,
    endereco TEXT
);

-- 3. Tabela de Usuários (extensão da tabela auth.users)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    email VARCHAR(100) NOT NULL UNIQUE,
    role user_role NOT NULL,
    condominio_id UUID REFERENCES condominios(id),
    unidade VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. Tabela de Dispositivos
CREATE TABLE IF NOT EXISTS dispositivos (
    device_id VARCHAR(50) PRIMARY KEY,
    condominio_id UUID NOT NULL REFERENCES condominios(id),
    unidade VARCHAR(50),
    localizacao VARCHAR(100)
);

-- 5. Tabela de Leituras dos Sensores
CREATE TABLE IF NOT EXISTS leituras_sensores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(50) NOT NULL REFERENCES dispositivos(device_id),
    temp_ida NUMERIC(5, 2),
    temp_retorno NUMERIC(5, 2),
    deltaT NUMERIC(5, 2),
    vazao_L_s NUMERIC(5, 2),
    potencia_kW NUMERIC(8, 4),
    energia_kWh NUMERIC(10, 4),
    reading_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Função para obter o perfil do usuário logado
CREATE OR REPLACE FUNCTION public.get_user_info()
RETURNS TABLE (user_role user_role, condominio_id UUID, unidade VARCHAR)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT role, condominio_id, unidade
    FROM public.users
    WHERE id = auth.uid();
$$;

-- 7. Ativar RLS na tabela de leituras
ALTER TABLE public.leituras_sensores ENABLE ROW LEVEL SECURITY;

-- 8. Política padrão para SELECT (apenas usuários autenticados)
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.leituras_sensores;
CREATE POLICY "Enable read access for authenticated users"
ON public.leituras_sensores FOR SELECT
TO authenticated
USING (true);

-- 9. Política para Comgás: Acesso a todas as leituras
DROP POLICY IF EXISTS "Comgas can view all readings" ON public.leituras_sensores;
CREATE POLICY "Comgas can view all readings"
ON public.leituras_sensores FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'comgas'
);

-- 10. Política para Zelador: Acesso às leituras do seu condomínio
DROP POLICY IF EXISTS "Zelador can view readings from their condominium" ON public.leituras_sensores;
CREATE POLICY "Zelador can view readings from their condominium"
ON public.leituras_sensores FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'zelador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = (
        SELECT d.condominio_id
        FROM public.dispositivos d
        WHERE d.device_id = leituras_sensores.device_id
    )
);

-- 11. Política para Morador: Acesso às leituras da sua unidade
DROP POLICY IF EXISTS "Morador can view readings from their unit" ON public.leituras_sensores;
CREATE POLICY "Morador can view readings from their unit"
ON public.leituras_sensores FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'morador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = (
        SELECT d.condominio_id
        FROM public.dispositivos d
        WHERE d.device_id = leituras_sensores.device_id
    )
    AND
    (SELECT unidade FROM public.get_user_info()) = (
        SELECT d.unidade
        FROM public.dispositivos d
        WHERE d.device_id = leituras_sensores.device_id
    )
);

-- 12. Política de Inserção: Permitir inserção de dados (via service_role ou authenticated)
-- Para inserção via frontend/dashboard, usamos authenticated
DROP POLICY IF EXISTS "Enable insert for bridge script" ON public.leituras_sensores;
CREATE POLICY "Enable insert for bridge script"
ON public.leituras_sensores FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.dispositivos d
        WHERE d.device_id = leituras_sensores.device_id
    )
);

-- 13. Índices para melhorar performance das consultas
CREATE INDEX IF NOT EXISTS idx_leituras_device_id ON public.leituras_sensores(device_id);
CREATE INDEX IF NOT EXISTS idx_leituras_reading_time ON public.leituras_sensores(reading_time DESC);
CREATE INDEX IF NOT EXISTS idx_leituras_device_time ON public.leituras_sensores(device_id, reading_time DESC);

-- 14. Comentários nas tabelas (opcional, mas útil)
COMMENT ON TABLE leituras_sensores IS 'Armazena as leituras dos sensores do ESP32';
COMMENT ON TABLE dispositivos IS 'Cadastro dos dispositivos ESP32';
COMMENT ON TABLE condominios IS 'Cadastro de condomínios';
COMMENT ON TABLE users IS 'Extensão da tabela auth.users com informações de perfil';

