-- Extensões do Schema para funcionalidades avançadas
-- Execute este script após o schema principal

-- 1. Tabela de Configurações do Sistema (para zeladores personalizarem)
CREATE TABLE IF NOT EXISTS configuracao_sistema (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    condominio_id UUID NOT NULL REFERENCES condominios(id),
    device_id VARCHAR(50) REFERENCES dispositivos(device_id), -- NULL = configuração geral do condomínio
    setpoint_temperatura NUMERIC(5, 2) DEFAULT 65.0,
    temp_min_critica NUMERIC(5, 2) DEFAULT 50.0,
    temp_max_critica NUMERIC(5, 2) DEFAULT 80.0,
    delta_t_minimo NUMERIC(5, 2) DEFAULT 5.0,
    potencia_maxima_kw NUMERIC(8, 4) DEFAULT 50.0,
    alerta_email BOOLEAN DEFAULT false,
    alerta_whatsapp BOOLEAN DEFAULT false,
    intervalo_medicao_segundos INTEGER DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_by UUID REFERENCES auth.users(id),
    UNIQUE(condominio_id, device_id)
);

-- 2. Tabela para armazenar dados meteorológicos
CREATE TABLE IF NOT EXISTS dados_meteorologicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condominio_id UUID NOT NULL REFERENCES condominios(id),
    temperatura_ambiente NUMERIC(5, 2),
    umidade NUMERIC(5, 2),
    pressao NUMERIC(7, 2),
    velocidade_vento NUMERIC(5, 2),
    descricao VARCHAR(100),
    reading_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Índices para dados meteorológicos
CREATE INDEX IF NOT EXISTS idx_meteo_condominio_time ON public.dados_meteorologicos(condominio_id, reading_time DESC);
CREATE INDEX IF NOT EXISTS idx_meteo_reading_time ON public.dados_meteorologicos(reading_time DESC);

-- 4. Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Trigger para atualizar updated_at na tabela de configurações
DROP TRIGGER IF EXISTS update_configuracao_sistema_updated_at ON public.configuracao_sistema;
CREATE TRIGGER update_configuracao_sistema_updated_at
    BEFORE UPDATE ON public.configuracao_sistema
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 6. Políticas RLS para configuracao_sistema
ALTER TABLE public.configuracao_sistema ENABLE ROW LEVEL SECURITY;

-- Comgás pode ver todas as configurações
CREATE POLICY "Comgas can view all system configs"
ON public.configuracao_sistema FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'comgas'
);

-- Zelador pode ver e editar configurações do seu condomínio
CREATE POLICY "Zelador can manage configs from their condominium"
ON public.configuracao_sistema FOR ALL
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'zelador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = configuracao_sistema.condominio_id
)
WITH CHECK (
    (SELECT user_role FROM public.get_user_info()) = 'zelador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = configuracao_sistema.condominio_id
);

-- Morador pode apenas visualizar configurações da sua unidade (se houver)
CREATE POLICY "Morador can view configs from their unit"
ON public.configuracao_sistema FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'morador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = configuracao_sistema.condominio_id
    AND
    (
        configuracao_sistema.device_id IS NULL
        OR
        EXISTS (
            SELECT 1 FROM public.dispositivos d
            WHERE d.device_id = configuracao_sistema.device_id
            AND d.condominio_id = (SELECT condominio_id FROM public.get_user_info())
            AND d.unidade = (SELECT unidade FROM public.get_user_info())
        )
    )
);

-- 7. Políticas RLS para dados_meteorologicos
ALTER TABLE public.dados_meteorologicos ENABLE ROW LEVEL SECURITY;

-- Comgás pode ver todos os dados meteorológicos
CREATE POLICY "Comgas can view all weather data"
ON public.dados_meteorologicos FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'comgas'
);

-- Zelador pode ver dados do seu condomínio
CREATE POLICY "Zelador can view weather from their condominium"
ON public.dados_meteorologicos FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'zelador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = dados_meteorologicos.condominio_id
);

-- Morador pode ver dados do seu condomínio
CREATE POLICY "Morador can view weather from their condominium"
ON public.dados_meteorologicos FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'morador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = dados_meteorologicos.condominio_id
);

-- Permitir inserção de dados meteorológicos (pode ser feito por serviço backend)
CREATE POLICY "Enable insert for weather data"
ON public.dados_meteorologicos FOR INSERT
TO authenticated
WITH CHECK (true);

-- 8. Ajustar políticas RLS de leituras_sensores para suportar condomínios sem sistema individualizado
-- A política atual já funciona, mas vamos melhorar para casos onde não há unidade específica

-- Nova política mais flexível para morador (suporta condomínios sem sistema individualizado)
DROP POLICY IF EXISTS "Morador can view readings from their unit" ON public.leituras_sensores;

-- Se o morador tem unidade, filtra por unidade. Se não tem, mostra dados do condomínio
CREATE POLICY "Morador can view readings from their unit or condominium"
ON public.leituras_sensores FOR SELECT
TO authenticated
USING (
    (SELECT user_role FROM public.get_user_info()) = 'morador'
    AND
    (SELECT condominio_id FROM public.get_user_info()) = (
        SELECT d.condominio_id
        FROM public.dispositivos d
        WHERE d.device_id = leituras_sensores.device_id
    )
    AND
    (
        -- Se não tem unidade definida, mostra todos os dispositivos do condomínio
        (SELECT unidade FROM public.get_user_info()) IS NULL
        OR
        -- Se tem unidade, filtra por unidade
        (SELECT unidade FROM public.get_user_info()) = (
            SELECT d.unidade
            FROM public.dispositivos d
            WHERE d.device_id = leituras_sensores.device_id
        )
        OR
        -- Se o dispositivo não tem unidade específica (sistema centralizado), permite acesso
        (
            SELECT d.unidade
            FROM public.dispositivos d
            WHERE d.device_id = leituras_sensores.device_id
        ) IS NULL
    )
);

-- 9. Comentários
COMMENT ON TABLE configuracao_sistema IS 'Configurações personalizáveis do sistema de aquecimento por condomínio/dispositivo';
COMMENT ON TABLE dados_meteorologicos IS 'Dados meteorológicos para comparação com consumo de energia';

